TARGET = STARTKIT
APP_NAME =
XCC_FLAGS = -g -report -Os -save-temps -fno-xta-info
USED_MODULES = module_xassert module_logging module_startkit_gpio

#=============================================================================
# The following part of the Makefile includes the common build infrastructure
# for compiling XMOS applications. You should not need to edit below here.

XMOS_MAKE_PATH ?= ../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
